name: "ğŸŒ Terraform Plan"

on:
  workflow_dispatch:    
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "ğŸ› ï¸ Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: "ğŸ“¦ Checkout code"
        uses: actions/checkout@v4

      # Setup Terraform CLI
      - name: "âš¡ Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5   # pick your version

      # Init Terraform
      # - name: "ğŸš€ Terraform Init"
      #   run: terraform -chdir=Infra init

      # Validate syntax
      - name: "ğŸ” Terraform Validate"
        run: terraform -chdir=Infra validate

      # Run Plan
      - name: "ğŸ“ Terraform Plan"
        run: terraform -chdir=Infra plan
